# Generated by Django 2.0 on 2018-03-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substrate',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
