# Generated by Django 2.0 on 2018-03-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phd', '0002_substrate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substrate',
            old_name='chimie',
            new_name='chemistery',
        ),
    ]
